# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

volumes:
  orderer.hec.edu.pk:
  peer0.hec.edu.pk:
  peer1.hec.edu.pk:
  peer0.pu.edu.pk:
  peer1.pu.edu.pk:
  peer0.lums.edu.pk:
  peer1.lums.edu.pk:

networks:
  hec-network:
    name: hec-university-network

services:
  # ===============================================
  #   ORDERER
  # ===============================================
  orderer.hec.edu.pk:
    container_name: orderer.hec.edu.pk
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/hec.edu.pk/orderers/orderer.hec.edu.pk/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/hec.edu.pk/orderers/orderer.hec.edu.pk/tls:/var/hyperledger/orderer/tls
      - orderer.hec.edu.pk:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - hec-network

  # ===============================================
  #   HEC PEERS
  # ===============================================
  peer0.hec.edu.pk:
    container_name: peer0.hec.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.hec.edu.pk
      - CORE_PEER_ADDRESS=peer0.hec.edu.pk:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hec.edu.pk:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hec.edu.pk:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hec.edu.pk:7051
      - CORE_PEER_LOCALMSPID=HECMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.hec:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/hec.edu.pk/peers/peer0.hec.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/hec.edu.pk/peers/peer0.hec.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer0.hec.edu.pk:/var/hyperledger/production
    ports:
      - 7051:7051
    depends_on:
      - couchdb.peer0.hec
    networks:
      - hec-network

  couchdb.peer0.hec:
    container_name: couchdb.peer0.hec
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984
    networks:
      - hec-network

  peer1.hec.edu.pk:
    container_name: peer1.hec.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.hec.edu.pk
      - CORE_PEER_ADDRESS=peer1.hec.edu.pk:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hec.edu.pk:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hec.edu.pk:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hec.edu.pk:8051
      - CORE_PEER_LOCALMSPID=HECMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.hec:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/hec.edu.pk/peers/peer1.hec.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/hec.edu.pk/peers/peer1.hec.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer1.hec.edu.pk:/var/hyperledger/production
    ports:
      - 8051:8051
    depends_on:
      - couchdb.peer1.hec
    networks:
      - hec-network

  couchdb.peer1.hec:
    container_name: couchdb.peer1.hec
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 6984:5984
    networks:
      - hec-network

  # ===============================================
  #   PUNJAB UNIVERSITY PEERS
  # ===============================================
  peer0.pu.edu.pk:
    container_name: peer0.pu.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.pu.edu.pk
      - CORE_PEER_ADDRESS=peer0.pu.edu.pk:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pu.edu.pk:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pu.edu.pk:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pu.edu.pk:9051
      - CORE_PEER_LOCALMSPID=PunjabUniversityMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.pu:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/pu.edu.pk/peers/peer0.pu.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/pu.edu.pk/peers/peer0.pu.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer0.pu.edu.pk:/var/hyperledger/production
    ports:
      - 9051:9051
    depends_on:
      - couchdb.peer0.pu
    networks:
      - hec-network

  couchdb.peer0.pu:
    container_name: couchdb.peer0.pu
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 7984:5984
    networks:
      - hec-network

  peer1.pu.edu.pk:
    container_name: peer1.pu.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.pu.edu.pk
      - CORE_PEER_ADDRESS=peer1.pu.edu.pk:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.pu.edu.pk:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pu.edu.pk:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pu.edu.pk:10051
      - CORE_PEER_LOCALMSPID=PunjabUniversityMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.pu:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/pu.edu.pk/peers/peer1.pu.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/pu.edu.pk/peers/peer1.pu.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer1.pu.edu.pk:/var/hyperledger/production
    ports:
      - 10051:10051
    depends_on:
      - couchdb.peer1.pu
    networks:
      - hec-network

  couchdb.peer1.pu:
    container_name: couchdb.peer1.pu
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 8984:5984
    networks:
      - hec-network

  # ===============================================
  #   LUMS PEERS
  # ===============================================
  peer0.lums.edu.pk:
    container_name: peer0.lums.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.lums.edu.pk
      - CORE_PEER_ADDRESS=peer0.lums.edu.pk:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.lums.edu.pk:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.lums.edu.pk:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lums.edu.pk:11051
      - CORE_PEER_LOCALMSPID=LUMSMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.lums:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/lums.edu.pk/peers/peer0.lums.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/lums.edu.pk/peers/peer0.lums.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer0.lums.edu.pk:/var/hyperledger/production
    ports:
      - 11051:11051
    depends_on:
      - couchdb.peer0.lums
    networks:
      - hec-network

  couchdb.peer0.lums:
    container_name: couchdb.peer0.lums
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 9984:5984
    networks:
      - hec-network

  peer1.lums.edu.pk:
    container_name: peer1.lums.edu.pk
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hec-university-network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.lums.edu.pk
      - CORE_PEER_ADDRESS=peer1.lums.edu.pk:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.lums.edu.pk:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lums.edu.pk:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.lums.edu.pk:12051
      - CORE_PEER_LOCALMSPID=LUMSMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.lums:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./crypto-config/peerOrganizations/lums.edu.pk/peers/peer1.lums.edu.pk/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/lums.edu.pk/peers/peer1.lums.edu.pk/tls:/etc/hyperledger/fabric/tls
      - peer1.lums.edu.pk:/var/hyperledger/production
    ports:
      - 12051:12051
    depends_on:
      - couchdb.peer1.lums
    networks:
      - hec-network

  couchdb.peer1.lums:
    container_name: couchdb.peer1.lums
    image: couchdb:3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 10984:5984
    networks:
      - hec-network

  # ===============================================
  #   CLI TOOL
  # ===============================================
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hec.edu.pk:7051
      - CORE_PEER_LOCALMSPID=HECMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hec.edu.pk/peers/peer0.hec.edu.pk/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hec.edu.pk/peers/peer0.hec.edu.pk/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hec.edu.pk/peers/peer0.hec.edu.pk/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hec.edu.pk/users/Admin@hec.edu.pk/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    depends_on:
      - orderer.hec.edu.pk
      - peer0.hec.edu.pk
      - peer0.pu.edu.pk
      - peer0.lums.edu.pk
    networks:
      - hec-network
